version: '3'
services:
  app:
    container_name: "docker-node-mongo"
    restart: "always"
    build: .
    ports:
      - "4000:4000"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    container_name: "mongo"
    image: mongo
    volumes:
      - .:/var/www
    ports:
      - 27017:27017